### ISSUE TITLE
Add support for user defined overwrites

### ISSUE THREAD

**Issue by dkarchmer** [iotile/foss_finder#23]
When tracking FOSS, we need to:

1.- Indicate which license we are using when the project is multi-license
2.- Be able to explain exceptions. 
3.- Be able to indicate that a given project is only used internally.

Foss finder should look for a `.foss` file on the analyzing project, and if found, parse and use to overwrite or append information related to the open source dependencies.

I am open for suggestions for what file format to use, but .json is probably one good option (so file should probably be called `.foss.json`. The file content count then be something like:

```
{
    "overwrites": [   
       {
          "project": "foo",
          "version": "2.1",
          "multiuse-license": "MIT"   
       },
       {
          "project": "bar",
          "version": "2.1",
          "license": "GPL-2.0",
          "linkage": "Dynamic, we use it as an imported python module",
          "justification": "This is a 3rd party python package that is dynamically linked against in one of our python products.  We do not modify the 'chardet' source code and since we dynamically link against it, it does not infect the rest of our product."   
       },
       {
          "project": "foobar",
          "version": "2.1",
          "usage": "internal"
       }
       ...
    ]
}
```

in the first example, we are simply specifying that for `foo` who has multiple licenses, we are using "MIT". 

For the second, we are documenting a justification for why it is ok to use a GPL license.

For the third, I am just documenting that the project is only used for internal use

If "foo" or "bar" were not found, then foss-finder should report an error. 

But we could also use this to add licenses that were not found by foss-finder but we know we are using. For that, we could also add an additional

```
{
    "overwrites": [],
    "additions": [
          {
               "project": "foobar",
               .... <whatever fields are needed>
          }
   ]
```

**Comment by nockty** [comment]
Ok, so we should definitely add new columns to the output csv file for this kind of usage. Maybe we should add a column for each possible field in `.foss.json`. So, based on your examples, the following columns would be added: _multiuse-license_, _linkage_, _justification_, _usage_. These columns would then be 'sparse', but I don't think it's a problem.

As I understand it, each object of the `"overwrites"` field should have at least the following attributes: `"project"` and `"version"`. When a row of the csv corresponds to this project and version, the script fills the columns that are defined in `.foss.json`.
For instance (based on your first example), when `NPM,foo,(BSD-2-Clause OR MIT OR Apache-2.0),2.1,` is added, then the column _multiuse-license_ gets filled with 'MIT'. But then, it doesn't overwrite anything (it just adds information) so I'm not sure I understood correctly.

The question would then be: should the additional columns be defined by the script or by the configuration `.foss.json` file? _i.e._ should we be able to define arbitrary columns in the `.foss.json` file? It seems it would make the file very flexible to add any kind of information. Then, it would make sense to have the user declare what the additional columns are at the beginning of the file, just like this:

```
{
    "columns": [
        "multiuse-license",
        "linkage",
        "justification",
        "usage",
    ],
    "overwrites": [   
       {
          "project": "foo",
          "version": "2.1",
          "multiuse-license": "MIT"   
       },
       ...
    ],
    "additions": [
        ...
    ]
}
```

(Or we could also parse the file a first time to find all the additional columns.)

As for the `"additions"` field, what I understand is: just add rows with these values. For instance, this object

```
{
    "project": "foobar",
    "registry": "NPM",
    "version": "4.2",
    "license": "MIT",
}
```

would add this row to the csv: `NPM,foobar,MIT,4.2,`.

Did I understand everything correctly? Let me know what you think about this.
